runner: SubProcesses/P1_Sigma_sm_gg_ttx/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttx/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttx/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make -j && make

FPTYPE=f: SubProcesses/P1_Sigma_sm_gg_ttx/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttx/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttx/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make -j FPTYPE=f && make FPTYPE=f


FPTYPE=d: SubProcesses/P1_Sigma_sm_gg_ttx/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttx/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttx/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make -j FPTYPE=d && make FPTYPE=d


clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make clean

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make cleanall