runner: SubProcesses/P1_Sigma_sm_gg_ttx/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttx/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttx/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make -j
	export MG5AMC_CARD_PATH=Cards/

clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make clean
	unset MG5AMC_CARD_PATH

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make cleanall
	unset MG5AMC_CARD_PATH