runner: SubProcesses/P1_Sigma_sm_gg_ttx/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttx/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttx/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make -j
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make

clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make clean

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttx/ && make cleanall