runner: SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttxgg/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttxgg/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttxgg/ && make -j
	export MG5AMC_CARD_PATH=Cards/
clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttxgg/ && make clean
	unset MG5AMC_CARD_PATH

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttxgg/ && make cleanall
	unset MG5AMC_CARD_PATH