runner: SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttxgg/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttxgg/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttxgg/ && make -j && make

clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttxgg/ && make clean

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttxgg/ && make cleanall
