runner: SubProcesses/P1_Sigma_sm_gg_ttxggg/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttxggg/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttxggg/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttxggg/ && make -j && make

clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttxggg/ && make clean

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttxggg/ && make cleanall
