runner: SubProcesses/P1_Sigma_sm_gg_ttxg/check_sa.cc SubProcesses/P1_Sigma_sm_gg_ttxg/PEP.hpp SubProcesses/P1_Sigma_sm_gg_ttxg/PEPPER.hpp
	cd SubProcesses/P1_Sigma_sm_gg_ttxg/ && make -j && make

clean:
	cd SubProcesses/P1_Sigma_sm_gg_ttxg/ && make clean

cleanall:
	cd SubProcesses/P1_Sigma_sm_gg_ttxg/ && make cleanall
